version: '3.8'

services:
  grass-api:
    platform: linux/amd64
    build: .
    container_name: grass-api
    volumes:
      - ./app:/app
      - ./grassdata:/grassdata
    ports:
      - "8000:8000"
    environment:
      - GRASS_DATA_DIR=/grassdata
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3